{% set version = "0.8.1" %}

package:
  name: dolfyn
  version: {{ version }}

source:
  fn: dolfyn-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/d/dolfyn/dolfyn-{{ version }}.tar.gz
  sha256: a40e543db68880c80f8af5f83df1f106a9c1286593e398d2cbf976fe9ae4d37b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - h5py

test:
  imports:
    - dolfyn
    - dolfyn.adp
    - dolfyn.adv
    - dolfyn.data
    - dolfyn.io
    - dolfyn.meta
    - dolfyn.tools

about:
  home: http://github.com/lkilcher/dolfyn
  license: Apache 2.0
  summary: 'Doppler Ocean Library for pYthoN.'

extra:
  recipe-maintainers:
    - ocefpaf
