{% set version = "0.8.3" %}

package:
  name: dolfyn
  version: {{ version }}

source:
  url:  https://pypi.io/packages/source/d/dolfyn/dolfyn-{{ version }}.tar.gz
  sha256: 7e7bed9b843efbfc0611af888d070291898f21a956a2345e6a471a0dad37322e

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - h5py

test:
  imports:
    - dolfyn
    - dolfyn.adp
    - dolfyn.adv
    - dolfyn.data
    - dolfyn.io
    - dolfyn.meta
    - dolfyn.tools

about:
  home: http://github.com/lkilcher/dolfyn
  license: Apache 2.0
  summary: 'Doppler Ocean Library for pYthoN.'

extra:
  recipe-maintainers:
    - ocefpaf
