{% set version = "0.11.0" %}

package:
  name: dolfyn
  version: {{ version }}

source:
  url:  https://pypi.io/packages/source/d/dolfyn/dolfyn-{{ version }}.tar.gz
  sha256: 978d38a2c01334cc82454930488b9aee86af11b1e1f061e055d113aaa294ad20

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - h5py
    - pydicth5

test:
  imports:
    - dolfyn
    - dolfyn.adp
    - dolfyn.adv
    - dolfyn.data
    - dolfyn.io
    - dolfyn.meta
    - dolfyn.tools

about:
  home: http://github.com/lkilcher/dolfyn
  license: Apache 2.0
  summary: 'Doppler Ocean Library for pYthoN.'

extra:
  recipe-maintainers:
    - ocefpaf
