travis:
  secure:
    BINSTAR_TOKEN: nEujr94753xJk8S4wbUiJuA+wfYB3FtyFGBEYSvzBEJg6UZuv/Tu+d4MkXBwx7Comka7MNED5/CJmnBtfbzi003EBNu1FgQKrummqBEpmL2y9mKgP95DfCcp5JrNd5a+21DkwvPj5pY6LCiE2BEPA8IdcwE8OK4kJNWZ4FktCpekZG6mYRnloaX6QrrqavrL7KW94w0a7YngUmqO9Kr+mqumIR/+x6cPS83lD/VuF3tlzHcU1Yzyx+4VC1WcKdTDJjZgBv0GvFfldG87cOR0LEK7xh7mtsZk0PreXDdWrcYKyGAgxr8ir088DDEtrDdthbJqizKj/71/hlvPqJ0lgcDz1gnaF7cvy9sou/zn8TvuoYbfjNriAkTRhyIibHEjDoZ7iGwVNCzjZqOcziK6COnlK18k44g0ZF1OrK5YcnrzrJKz2a7WfuiIQciWbifdisik88pusAx44nZe/f92DRmUPW6v45EkVwdVOm5mwlXGbGYXQI83gtGZeumHO+5kb9nKoFSTymkVnr0s/lfD42lkuk+lI19k4gT1KUkDWgjG4K3mf6xaZ6JvjfEknj7qawlvzoZ42z4o39qa7tj6ygXc/XnJj1E1C55u04irna5baTXBZjj80V6mA+zym6SSmw7xYeZdgSXGxuHw/7tpti/z0Zei/RsRo4VAqAthLOw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
